### PR TITLE
Added info on google calendar

### PR DESCRIPTION
**Pull request by ehsteve**
This addresses issue #60.

### CODE REVIEW

**Comment by ehsteve** [comment]
ping @Cadair

**Comment by Cadair** [comment]
Let me add the events then I will merge this.

**Comment by dpshelio** [comment]
I had added the dev calls for at least three months... but I don't want this calendar only used for the dev-teleconf but to show where sunpy representation will be present (conferences, workshops,...)

**Comment by Cadair** [comment]
yes, we should keep adding other things to it.

I am :+1: on this. @dpshelio I will let you press the button.

**Comment by ehsteve** [comment]
Great idea @dpshelio 👍. Will be nice to have one place to look for this stuff.

**Pull request merged**
