### PR TITLE
Author attributes update

### PR DESCRIPTION
**Pull request by prateekiiest**

### CODE REVIEW

**Comment by dpshelio** [comment]
Could you describe why this would be better? Are the links created for the users? Or allows us to filter the posts by them? Wouldn't be better to take automatically the name based on their github name?  I just wonder what happens when a post writer doesn't have github.

**Comment by dpshelio** [comment]
Also, I would have committed not file by file, but commit all the files by the same user as one, as that's the meaninful change. By commits like "update file_x.md" I cannot get an idea of what has changed.

**Comment by prateekiiest** [comment]
I am sorry for that @dpshelio .
I just replaced each author name by his github id.

**Comment by prateekiiest** [comment]
My idea was that we create a list of names of the members of the community with an embedded link in each name which will direct to the posts they have written.
By their github link users can check their contribution graph for Sunpy.

**Comment by prateekiiest** [comment]
Also, if users have any query regarding any blog post, they can contact the author through their github profile.

**Comment by prateekiiest** [comment]
@dpshelio ,in case if a post writer doesn't have any github profile, we can update the link to his blog or personal website.

**Comment by nabobalis** [comment]
Overall, there are too many commits, even for me and you can ask Cadair how I like to commit. 

When you are done, you will need to git rebase and squash all but a few of the commits.

**Comment by prateekiiest** [comment]
Yeah, I kind of understand, like merging 30 files or so.
Ok I'm squashing some of them :)

**Comment by ehsteve** [comment]
Wouldn't this be an easier way to handle this? https://help.github.com/articles/mentions-on-github-pages/

**Comment by ehsteve** [comment]
@dpshelio not sure how a post writer would write a post without a github account! It would mean that someone with a github account would need to submit the PR for them. We've never encountered that so far. Not sure that we need to worry about that or support that right now.

**Comment by prateekiiest** [comment]
And how will we be accessing the authors ?
Like @author_name?

**Comment by nabobalis** [comment]
@ehsteve Well if worst came to worse, someone could submit the PR on their behalf.

**Comment by ehsteve** [comment]
@prateekiiest I would suggest that the @ mention is enough and we don't need the author's name IRL (though I do suggest that all profile accounts have a real name attached ahem @wafels!).

**Comment by ehsteve** [comment]
@Cadair @DuyguKeskek I still think this would be neat though the implementation here was not great.

**Comment by DuyguKeskek** [comment]
@ehsteve I know that and I will try to enhance the blogging system :)

**Pull request closed without merging**
