### PR TITLE
Blog post for pyastro16

### PR DESCRIPTION
**Pull request by ehsteve**
Anything else that should be mentioned @Cadair?

### CODE REVIEW

**Comment by Cadair** [comment]
haha you beat me to it. Yeah we should expand out a bit more, I will try and work on it before the end of the week.

**Comment by ehsteve** [comment]
@Cadair ping!

**Comment by dpshelio** [comment]
yeah! this should be a little bit with more detail... why was good? why should anyone in sunpy apply next year? which things were gained for sunpy (eg. py3)?

**Comment by ehsteve** [comment]
This is becoming a stale blog post!

**Comment by ehsteve** [comment]
updated text to allow for the possibility of another post. Please post now so it is time-relevant.

**Pull request merged**
