### PR TITLE
Applied minor styling changes on home page

### PR DESCRIPTION
**Pull request by DuyguKeskek**
I redesigned the current version text since it should be placed under the installation button.

Before :

before

After:

after

### CODE REVIEW

**Comment by Cadair** [comment]
How about putting it in the button? "Install SunPy v0.7.7"

**Comment by DuyguKeskek** [comment]
@Cadair I don't recommend putting it in the button since the call-to-action button may seem more complex. It should remain simple. I like the way that how [bootstrap website](http://getbootstrap.com/) place it. It is okey if you still prefer putting this in the button, I can change it.

**Comment by souravc4** [comment]
@DuyguKeskek : I'm not sure it looks better that way(below the install button) with the current color scheme.
@Cadair :  not a good idea imo as the motive initial motive was to display the version which was current version of sunpy, moreover it isn't neat to have a long text in a button.

**Comment by souravc4** [comment]
if you ask me, i would prefer it to have the current way, though the `font-size` can be increased a bit(`12` is good) when *display-width*<768px

**Comment by DuyguKeskek** [comment]
@souravc4 It is not the appropriate way to place the version info under the project name and it is also not common. The color scheme is already a problem since the installation button and the color of the background image are so close to each other. The complementary color should be used effectively. I just tried to enhance the general view according to the current website and my designer perspective, but we can still work on it.

**Comment by souravc4** [comment]
i agree about the color-scheme part, it would be better if the button has a shade of blue/purple but again the corresponding `:hover` selectors will need to be worked upon from scratch, that'll would require a separate PR in my opinion.

**Comment by DuyguKeskek** [comment]
@souravc4 Your approach is good, but in my opinion the button should not be blue or purple since they are not used as the complementary color for the entire website and it will cause inconsistency. I think this PR is enough with maybe some enhancements to be implemented later and after discussing with the mentors.

**Comment by nabobalis** [comment]
Could the version number  be changed to black instead? For me, it merges into the background a bit too easily. 

Also the text is now a bit too close to the title for my liking as well.

**Comment by DuyguKeskek** [comment]
@nabobalis I can also close this PR since it is not that useful.

**Comment by nabobalis** [comment]
@DuyguKeskek Yeah, I'm just getting the current site into a state where all PRs on it are closed since we plan to burn this down in some form.

**Pull request closed without merging**
