### PR TITLE
Added NumFOCUS logo to website

### PR DESCRIPTION
**Pull request by DuyguKeskek**
Congrats on your new sponsorship :+1:   I want to resolve the issue #86 

Currently, It looks like :  (Inspired from [astropy](http://www.astropy.org/) and [fenicsproject](https://fenicsproject.org/) and the footer bar is inspired from [quantecon](https://quantecon.org/) ) 

About section : 

about

Blog section : (The footer appears on the about,blog,contribute, and help section)

blog

### CODE REVIEW

**Comment by ehsteve** [comment]
👍

**Comment by ehsteve** [comment]
I think it might be neat to also have it in the footer bar like this [site](https://quantecon.org).

**Comment by DuyguKeskek** [comment]
@ehsteve It's a great idea :) I will add a footer and customize it asap. :+1:

**Comment by ehsteve** [comment]
thanks @DuyguKeskek!

**Comment by DuyguKeskek** [comment]
Hello @ehsteve!  I added the footer bar, can you please have a look at it ?

**Comment by ehsteve** [comment]
@DuyguKeskek looks really good! One small consideration, might it be better to use svgs instead of pngs?

**Comment by DuyguKeskek** [comment]
Thanks for your review @ehsteve :) I also prefer using svgs to have smaller file sizes and increased speed. 
I will convert them :+1:

**Comment by ehsteve** [comment]
@DuyguKeskek A quick look around and I can't find svg version of the numfocus logo. Any luck on your end? I can email numfocus and ask directly.

**Comment by souravc4** [comment]
Hi @DuyguKeskek, nice work overall, but might I suggest using a current colour code from the website (#444444) or (#f7f7f9) for the footer - (#e5e5e5) looks a bit out of sync for me.

**Comment by souravc4** [comment]
Also since we can't find the SVG originals of the numfocus logo, I would suggest using this white text png(http://numfocus.wpengine.com/wp-content/uploads/2017/03/1457562110.png) which they themselves use for their website(numfocus.org).

**Comment by souravc4** [comment]
Note that png is stored on their private server it seems, also manual conversion of png to svg just for the sake of it wouldn't be recommended. @ehsteve

**Comment by DuyguKeskek** [comment]
@ehsteve Good news ! I found the svg logo :) [Fenicsproject](https://fenicsproject.org/wp-content/uploads/2016/10/NumFocus_2C_CMYK.svg) already makes use of it. I replaced the pngs with the svg and committed :+1:

**Comment by DuyguKeskek** [comment]
Hi @souravc4 ! Thanks for appreciating my work :) If we make the footer dark, the numfocus logo will not be so clear. It is suitable to use #f7f7f9 for the footer, but I made the footer consistent with the border color that is #e5e5e5 and I think it looks better. Also, I was already using that white text png of the numfocus website. Thanks for your recommendations !

**Comment by souravc4** [comment]
I meant for the `numfocus-logo.png` which u used in the about section. Since I can't find an official repo for numfocus logo and a svg original isn't available in their [website's repo](https://github.com/numfocus/numfocus.org/tree/master/theme/static/img) i would consider sticking to their png for originality purposes.

**Comment by DuyguKeskek** [comment]
@souravc4 Since Fenicsproject already uses this, I think there won't be any problem. - also it is way better than the png one in terms of resolution -

**Comment by ehsteve** [comment]
ping @Cadair

**Pull request merged**
