### PR TITLE
Author names link to github under blog posts

### PR DESCRIPTION
**Pull request by prateekiiest**
Blog author names should link to their github profile.
This is done by creating a structure in the _config.yml file

`authors:
        name1:
            display_name : "sfdjvsb" 
             github: "github link"
`

I haven't done for author_names till now in order to test.

### CODE REVIEW

**Comment by prateekiiest** [comment]
The author names under _posts need to updated to github id , since author attributes is by github id.

**Comment by nabobalis** [comment]
Can you attach a screen shot of the blog? 
When I merge this into mine, the names seem to disappear from the blog posts from the blog overview. Admittedly, the version I have running right now is pretty messy.

**Comment by prateekiiest** [comment]
Ok, I have to build the page locally for that and recently I am not able to install RedCloth for building the page.

**Comment by nabobalis** [comment]
Yeah the gemlock file is pretty out of date. Hopefully that can be fixed soon. The other PRs will be merged I think this weekend.

**Comment by prateekiiest** [comment]
So, I'm not able to like build the page locally and see for myself.
At most for link updates for the html files, I have no choice than the Google Developer Tools.
So what to do?

**Comment by nabobalis** [comment]
Right now, make the changes and when the other PRs are merged, you can merge in master and test.

**Comment by prateekiiest** [comment]
screenshot 2017-04-07 17 51 53

For example clicking on the name Steven Christe, it will link to the corresponding github repo

**Comment by nabobalis** [comment]
@prateekiiest you can now merge in master. It might cause some issues for you though.

**Comment by Cadair** [comment]
you probably want to rebase this.

**Comment by prateekiiest** [comment]
Conflicts ?
Is it due to #76

**Comment by nabobalis** [comment]
Yeah, I moved the posts into year subdirectories.

**Comment by prateekiiest** [comment]
I am opening a seperate PR for this.

**Comment by nabobalis** [comment]
So you will close this PR?

**Comment by prateekiiest** [comment]
yes , I'm closing this.

**Comment by prateekiiest** [comment]
@nabobalis do you know Simon Liedtke's git profile link?

**Pull request closed without merging**
