### PR TITLE
Change download links to install instructions.

### PR DESCRIPTION
**Pull request by Cadair**
This follows from sunpy/sunpy#1181 and changes the download links to a link to the installation instructions.

### CODE REVIEW

**Comment by Cadair** [comment]
I am going to merge this now 0.6 is out, other things can be done after,

**Comment by ehsteve** [comment]
This was already in my PR #48!

**Comment by Cadair** [comment]
Sorry!!  I just wanted to change the main link, I forgot about your other PR.

it should not be that hard to integrate my changes into your PR though, I think there is only a one line conflict.

**Comment by ehsteve** [comment]
Yes I know. It's just the principle of the thing!

**Comment by Cadair** [comment]
:D This PR has been here for a long time waiting for 0.6!

**Pull request merged**
