### PR TITLE
Add a gallery button to the home page

### PR DESCRIPTION
**Pull request by Cadair**

### CODE REVIEW

**Comment by nabobalis** [comment]
But i do want sunpy in the last button :( SYMMETRY IS NICE

**Comment by nabobalis** [comment]
Should not just remove travis?

**Comment by nabobalis** [comment]
Should I spam the PR?

**Comment by Cadair** [comment]
I think it's a good idea to keep Travis building it as a test. I am not sure the Netlify logs are public.

**Comment by nabobalis** [comment]
How about:  `Install SunPy, Tour of SunPy, Experience SunPy`

**Pull request merged**
