### PR TITLE
Sunpy Presentations and Talks Upload on the Site

### PR DESCRIPTION
**Pull request by prateekiiest**
I uploaded some on the Sunpy videos and presentation links on the website.
I hope it will be great.
Any improvements that are needed in the design?
@Cadair 
@dpshelio

### CODE REVIEW

**Comment by prateekiiest** [comment]
screenshot 2017-04-28 14 57 30

Looks like this.
@dpshelio

**Comment by prateekiiest** [comment]
screenshot 2017-04-28 14 58 36

**Comment by prateekiiest** [comment]
@nabobalis 
ok?

**Comment by nabobalis** [comment]
SunPy needs to have a capital P. 

The first line implies the topic of the talk was Python in Astro/Scipy. Those were the places/workshops.

**Comment by prateekiiest** [comment]
oh, that's some mistake I'm doing everywhere. :P
So should I remove it then and instead include "Workshops attended by the Community like Python in Astro" or something like that?

**Comment by nabobalis** [comment]
Yeah, something like that would be more accurate.

**Comment by prateekiiest** [comment]
@nabobalis , i have updated the description

**Pull request merged**
