### PR TITLE
Removed overlap of header in "About" and "Contribute" with navbar

### PR DESCRIPTION
**Pull request by souravc4**

### CODE REVIEW

**Comment by souravc4** [comment]
Overlap occurs on clicking on any sidebar menu item eg. on clicking *The Team* in "About" page
**earlier**
padding earlier
**after**
padding after

**Comment by souravc4** [comment]
@Cadair @dpshelio

**Comment by nabobalis** [comment]
This was one of the things I overlooked in the merge. I think it meant to be 55pt.

**Comment by souravc4** [comment]
you did a tremendous job, I'll excuse it :P :P

**Comment by nabobalis** [comment]
The title is a bit too close to the header for me. It just needs a little bit more.

**Comment by souravc4** [comment]
yes i agree

**Comment by souravc4** [comment]
done @nabobalis looks good now (Y)

**Pull request merged**
