### PR TITLE
help section Docs link updated 

### PR DESCRIPTION
**Pull request by prateekiiest**
Issue #91

### CODE REVIEW

**Comment by prateekiiest** [comment]
@Cadair issue #8 
I believe updating this link on the help page will be good
http://docs.sunpy.org/en/latest/dev.html#sphinx

Should I update it in this PR itself or open a seperate PR for this?

**Comment by nabobalis** [comment]
@prateekiiest What needs changing?

**Comment by prateekiiest** [comment]
@nabobalis , I changed https to http in the links as it was showing a privacy error when opening the webpage

**Comment by nabobalis** [comment]
Sorry, I was referring to issue #8. 

The docs does mention, somewhat briefly, how to make the docs build locally.

**Pull request merged**
